jobs:
  - job: CopyFiles
    steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(BUILD.REPOSITORY.LOCALPATH)"
          TargetFolder: "$(Build.ArtifactStagingDirectory)"
        displayName: "Copy Files to: dis"

      - powershell: |
          ls $env:BUILD_REPOSITORY_LOCALPATH
          write-host "-------------------------------"
          ls $env:Build_ArtifactStagingDirectory
        displayName: "PowerShell Script"

  - job: Linux
    pool:
      vmImage: "ubuntu-16.04"

    strategy:
      matrix:
        Python27:
          python.version: "2.7"
        Python36:
          python.version: "3.6"
      maxParallel: 2

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
          architecture: "x64"

      - script: |
          pip install --upgrade pip
          pip install pytest
        condition: succeededOrFailed()
        displayName: "Install cookiecutter"

      - script: |
          pytest
        displayName: "Install IoT Edge Module and Run tests with pytest"

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: "**/test-results.xml"
          testRunTitle: "Publish test results for Python $(python.version)"
